name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: docker Build
      run: docker build -t dockertest .

    - name: Tag
      run: docker tag dockertest:latest 594585741510.dkr.ecr.ap-northeast-2.amazonaws.com/dockertest:latest

    - name: push image to Amazon ECR
      run: docker push 594585741510.dkr.ecr.ap-northeast-2.amazonaws.com/dockertest:latest